# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CauD7nfwC07F10mnSJr1XBft6uVpl0VT
"""



import argparse
from torchvision import datasets, models
from pretrained_cnn import PretrainedCNN
from transform import get_transforms

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--lr', type=float, default=1e-4)
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--freeze_percent', type=float, default=0.9)
    parser.add_argument('--epochs', type=int, default=2)
    parser.add_argument('--l2', type=float, default=0.0005)
    parser.add_argument('--data_path', type=str, default='./inaturalist_12K')
    args = parser.parse_args()

    train_transform, val_transform = get_transforms()
    trainset = datasets.ImageFolder(root=f'{args.data_path}/train', transform=train_transform)
    valset = datasets.ImageFolder(root=f'{args.data_path}/val', transform=val_transform)

    model = models.resnet50(pretrained=True)
    cnn_model = PretrainedCNN(trainset, valset, model, batch_size=args.batch_size, freeze_percent=args.freeze_percent)
    cnn_model.train(epochs=args.epochs, lr=args.lr, weight_decay=args.l2)

